using AutoTrading.Application.Common.Interfaces;
using AutoTrading.Domain.Entities;
using AutoTrading.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace AutoTrading.Infrastructure.EnumAutoGenerated;

public class CodeCategoryService : ICodeCategoryService
{
    private readonly IApplicationDbContext _context;

    public CodeCategoryService(IApplicationDbContext context)
    {
        _context = context;
    }
    
    public async Task<List<CodeCategory>> GetCodeCategories()
    {
        return await _context.CodeCategories.ToListAsync();
    }

    public async Task<List<Code>> GetCodesByCodeCategoryId(long codeCategoryId)
    {
        return await _context.Codes.Where(x => x.CodeCategoryId == codeCategoryId).ToListAsync();
    }
}